apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: server
  generateName: server-
spec:
  pipelineRef:
    name: server
  params:
    - name: MAVEN_MIRROR_URL
      value: http://nexus:8081/content/groups/public/
    - name: push-to-prod
      value: "false"
  workspaces:
  - name: git-source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: gitops-manifests
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: maven-settings
    configmap:
      name: maven-settings
  - name: newman-env
    configMap:
      name: newman-env