apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: server
  generateName: server-
spec:
  pipelineRef:
    name: server
  params:
    - name: MAVEN_MIRROR_URL
      value: http://nexus:8081/content/groups/public/
    - name: push-to-prod
      value: "false"
    - name: acs-secret
      value: acs-secret
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: server-source
  - name: maven-settings
    configmap:
      name: maven-settings
  - name: newman-env
    configMap:
      name: newman-env