apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: server-push-prod-pr
  generateName: server-push-prod-pr-
spec:
  serviceAccountName: github-pipeline
  pipelineRef:
    name: push-prod-pr
  params:
    - name: image_dest_tag
      value: 3f35360-1705790019
    - name: image_dest_url
      value: quay.io/gnunn/server
    - name: cluster
      value: local.home
    - name: app
      value: server
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: manifest-source