apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-catalog
  namespace: product-catalog-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-dev
            path: components/app/product-catalog-app/overlays/dev
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-test
            path: components/app/product-catalog-app/overlays/test
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-prod
            path: components/app/product-catalog-app/overlays/prod
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: apps-product-catalog
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config
        targetRevision: refactor
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops