apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newName: quay.io/gnunn/client
  newTag: fff9592-2fbdBT1Wxzx9uBS8uCeR2uyIsyr
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: de1031a-2fmawGLnBBNTJlka40yw8V5g7bx

resources:
- ../../../../environments/overlays/dev
