apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newName: quay.io/gnunn/client
  newTag: fff9592-2fbdBT1Wxzx9uBS8uCeR2uyIsyr
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: a6d2c4f-2g6vlD5wYkqoBr81OWmrSTrNzHp

resources:
- ../../../../environments/overlays/dev
