apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newName: quay.io/gnunn/client
  newTag: 6f50f7d-3027303906
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: 5a16d08-1469189302

resources:
- ../../../../environments/overlays/dev
- test-blacklist.yaml
