apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newName: quay.io/gnunn/client
  newTag: b8a2b2a-3993399755
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: 7395c16-61014457
resources:
- ../../../../environments/overlays/dev
