apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: server
  name: server
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: server:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:11
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: e2tuQR5hpfzBqSSf90wx
    type: GitHub
  - generic:
      secret: FKVcemYnq1uk-NNZFMtO
    type: Generic