apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: server-post-prod
spec:
  workspaces:
    - name: newman-env
    - name: slack-secret
      optional: true
  tasks:
    - name: prod-test
      taskRef:
        name: newman
      params:
        - name: COLLECTION
          value: https://raw.githubusercontent.com/gnunn-gitops/product-catalog-server/master/tests/product-catalog-server-tests.json
        - name: ENVIRONMENT
          value: newman-prod-env.json
      workspaces:
        - name: newman-env
          workspace: newman-env
        - name: slack-secret
          optional: true
  finally:
    # - name: notify
    #   taskRef:
    #     name: send-to-webhook-slack
    #   when:
    #     - input: "$(workspaces.slack-secret.bound)"
    #       operator: in
    #       values: ["true"]
    #   params:
    #     - name: message
    #       value: "Production has been synchronized by ArgoCD, test status: $(tasks.prod-test.status)"
    #   workspaces:
    #     - name: slack-secret
    #       workspace: slack-secret
    # Add when pipelines updated to version of Tekton that supports using when expressions
    - name: notify-succeeded
      when:
        - input: $(tasks.prod-test.status)
          operator: in
          values: ["Succeeded"]
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: message
          value: "SUCCEEDED: Production has been synchronized by ArgoCD"
      workspaces:
        - name: slack-secret
          workspace: slack-secret
    - name: notify-failed
      when:
        - input: $(tasks.prod-test.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: message
          value: "FAILED: Production has been synchronized by ArgoCD"
      workspaces:
        - name: slack-secret
          workspace: slack-secret