apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: product-catalog
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: product-catalog