apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgAEtnJ4CwCHdjZQm2nRPyDDE75WW6uXXMOmF1rTn5+GshiGu420btHbpSUvB6vPKkiIN1VWmkO0TudzjUCYxCmAviEHv6mOymL4BKdGEpQij7aEIRuunUhWbhhCJrn43BgFSGk1g/aZQJ3GiLcFPAZWs8m2w3//czXSnm/d5sy/HkTNLsOFgOzrUNcfOjyRpUjHRW36SVzJCakEVPNa1rskWflha2qk+d1hGgh4rkW6Qs0sXExIclEyrIu6N4Gbrb8tSzeg0YGNZdGNhHfnIV7cToksTc3WoVfGsNRI8UeeD5XmHbLePa3NaeqLg+jn3tp+lSbTkt3cOff9Ia8RtvugwFhrVE4k9mGEa4UnuxnH90M1ELSreWblcoUw+JQ2GmclHTX5N7PoZl0zvxn6twVehBNgW5B3f7Sfi/OgQPyM+vwAOhUcMA7wyNwSBWrzdC5Kqi73HoEJsdDIa6Oejny4agNfGkfZz7uyUMpmS3agoL/ATGEVDmSiEXz6GEtrTRM9CRwUPNg2Nz40Vm5ssu3H9gmNT1y3obMPvnQPEk9bYFTBwzpPaHqVidEwNVLIIAWiLe0zjiz1h9TcR7pNEPDnsoe1mWw1J2edzCWNA2HVkkTYF9RT8/AEKRuTFXwSAQC+gok5VyTNjmvY4jNtlTjqvI/23JGgdxCpHxvTGYH/DE6rFiGdjhD9LxvlRqVyIARnysgZe0V8nwEf04AZIfAeBL5xGujWl3gXFqo4pErlun/iCkTjFi+CXuCGLk4eRgjvBuAxVEZ4dNeHmCdZjm29CtS0VdaLolIomjQont2zHy0n
  template:
    metadata:
      creationTimestamp: null
      name: slack-deployments-webhook
      namespace: product-catalog-cicd
    type: Opaque