apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: roxsecrets
  namespace: product-catalog-cicd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: product-catalog
  target:
    name: roxsecrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: ACS_SCAN_IMAGE
