apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: product-catalog
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .docker_secret | toString }}"
    name: dest-docker-config
    creationPolicy: Owner
  data:
  - secretKey: docker_secret
    remoteRef:
      key: DOCKER_CONFIG_JSON
