apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: product-catalog
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: dopplerToken
            name: eso-token-product-catalog
