apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github
  namespace: product-catalog-cicd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: github
    template:
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      type: kubernetes.io/basic-auth
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: GITHUB