apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: slack-deployments-webhook
  data:
    - secretKey: url
      remoteRef:
        key: SLACK_DEPLOYMENTS
