apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: upload-sbom
  namespace: product-catalog-cicd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: product-catalog
  target:
    name: upload-sbom
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: UPLOAD_SBOM_OIDC
