apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-template
data:
  workspace-template.yaml: |
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi