{
 "title": "Server Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "product-catalog-dev,product-catalog-test,product-catalog-prod"
   },
   { "name": "api", "label": "API", "query": "product,category" }
  ]
 },
 "panels": [
  { "title": "API Performance for $api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "api" },
  {
   "title": "Method Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_count.*\",method=~\".+\",type=\"counter\", namespace=\"$namespace\", api=\"$api\"}[5m])) by (method)"
    }
   ]
  },
  {
   "title": "Performance 95% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_seconds.*\",method=~\".+\",type=\"perf\", namespace=\"$namespace\", api=\"$api\", quantile=\"0.95\"}[5m])) by (method)"
    }
   ]
  },
  {
   "title": "Performance 75% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_seconds.*\",method=~\".+\",type=\"perf\", namespace=\"$namespace\", api=\"$api\", quantile=\"0.75\"}[5m])) by (method)"
    }
   ]
  },
  { "title": "API Performance for $api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Method Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_count.*\",method=~\".+\",type=\"counter\", namespace=\"$namespace\", api=\"$api\"}[5m])) by (method)"
    }
   ]
  },
  {
   "title": "Performance 95% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_seconds.*\",method=~\".+\",type=\"perf\", namespace=\"$namespace\", api=\"$api\", quantile=\"0.95\"}[5m])) by (method)"
    }
   ]
  },
  {
   "title": "Performance 75% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_seconds.*\",method=~\".+\",type=\"perf\", namespace=\"$namespace\", api=\"$api\", quantile=\"0.75\"}[5m])) by (method)"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_time_total_seconds{namespace=\"$namespace\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_total{namespace=\"$namespace\"}[5m])) by (pod,name)"
    }
   ]
  }
 ]
}