apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../environments/overlays/cicd

resources:
- pipeline-rolebinding.yaml
- argocd-env-cm.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

# patchesJson6902:
#   - path: patch-pvc-block.yaml
#     target:
#       group: ""
#       kind: PersistentVolumeClaim
#       name: m2-cache
#       version: v1
  # - path: patch-pvc-block.yaml
  #   target:
  #     group: ""
  #     kind: PersistentVolumeClaim
  #     name: npm-cache
  #     version: v1