apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
# Supporting infra
- m2-cache-pvc.yaml
# - npm-cache-pvc.yaml
- dependency-cache-pvc.yaml
# Tekton tasks
- task-git.yaml
- task-yq.yaml
- https://github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/maven/overlays/m2-cache
- task-npm.yaml
- task-npm-quality.yaml
- task-binary-s2i.yaml
- task-push-image.yaml
- task-deploy.yaml
- https://github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/newman/base
- task-create-pr.yaml
- task-tekton.yaml
- task-generate-id.yaml
- task-send-to-webhook-slack.yaml
- task-kustomize.yaml
- argocd-sync-and-wait-task.yaml