# Adapted from Tekton Catalog item
# https://github.com/tektoncd/catalog/tree/main/task/send-to-webhook-slack/0.1
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-webhook-slack
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: messaging
spec:
  description: >-
    These tasks post a simple message to a slack channel.
    This task uses Incoming Webhooks of slack to send the message.
  params:
  - name: message
    type: string
    description: plain text message
  workspaces:
  - name: slack-secret
    optional: true
  steps:
  - name: post
    image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.10
    script: |
      #!/bin/sh

      # Always echo message locally for logging purposes
      echo "$(params.message)"

      if [ $(workspaces.slack-secret.bound) == "true" ] ; then
        if [ -f "$(workspaces.slack-secret.path)/url" ]; then
          printf "\nSending to slack...\n\n"
          URL=$(cat $(workspaces.slack-secret.path)/url)

          echo "Sending slack message"

          /usr/bin/curl -X POST -H 'Content-type: application/json' --data '{"type": "mrkdwn", "text":"$(params.message)"}' $URL
          exit 0
        fi
      fi

      echo "Note: Slack message was not sent as it was not configured"