apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
  - name: source
  steps:
    - name: npm-install
      image: registry.redhat.io/ubi8/nodejs-14:latest
      command:
        - /bin/sh
        - -c
      args:
        - npm install --package-lock
      workingDir: $(workspaces.source.path)
    - name: build
      image: registry.redhat.io/ubi8/nodejs-14:latest
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: $(workspaces.source.path)
    - name: copy-dist
      image: registry.redhat.io/ubi8/nodejs-14:latest
      command:
        - /bin/sh
        - -c
      args:
        - cp -R ./dist/* $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
    - name: save-commit-sha
      image: docker.io/maven:3.6.3-jdk-8
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          mkdir -p $(workspaces.source.path)/git-sha
          git rev-parse --short HEAD | tee $(workspaces.source.path)/git-sha/commit-id
      workingDir: $(workspaces.source.path)