apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-image
spec:
  params:
  - name: src_image
    type: string
  - name: dest_image
    type: string
  - name: dest_tags
    type: string
    default: ""
  steps:
    - name: run-commands
      image: quay.io/skopeo/stable:v1.13.2
      script: |
        #!/usr/bin/env bash

        if [ "$(params.dest_tags)" != "" ];
        then

          tags=$(params.dest_tags)
          for i in ${tags//,/ }
          do
            echo "Copying image docker://$(params.src_image) to docker://$(params.dest_image):$i"
            skopeo copy --src-tls-verify=false --dest-tls-verify=false docker://$(params.src_image) --dest-authfile=/tekton/creds-secrets/dest-docker-config/.dockerconfigjson docker://$(params.dest_image):$i
          done
        fi