apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: variables-from-k8s
spec:
  results:
    - name: acs-central-endpoint
  workspaces:
    - name: acs-central
      optional: true
  steps:
    - name: get-variables
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env sh
        if [ $(workspaces.acs-central.bound) == "true" ] ; then
          cat $(workspaces.acs-central.path)/rox_central_endpoint > $(results.acs-central-endpoint.path)
        else
          echo "not-set" > $(results.acs-central-endpoint.path)
        fi