apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kustomize
spec:
  params:
    - name: image-name
      type: string
      description: "The placeholder image in the deployment to be replaced."
    - name: new-image
      type: string
      description: "The image to update the deployment with."
    - name: new-tag
      type: string
      description: "The image to tag update the deployment with."
    - name: overlaypath
      type: string
      description: "Path to the overlay directory."
  steps:
    - name: kustomize
      workingDir: $(workspaces.source.path)
      image: quay.io/redhatworkshops/kustomize-task:v4.0.5
      script: |
        #!/usr/bin/env /bin/sh
        echo "Kustomizing image"
        echo "Running: kustomize edit set image $(params.image-name)=$(params.new-image):$(params.new-tag)"
        cd $(params.overlaypath)
        kustomize edit set image $(params.image-name)=$(params.new-image):$(params.new-tag)
  workspaces:
    - name: source