apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-quality
spec:
  workspaces:
  - name: source
  params:
  - name: SONAR_SERVER_URL
    default: "http://sonarqube.dev-tools:9000"
    description: The location of sonarqube, passed as an environment variable SONAR_SERVER_URL
  steps:
    - name: quality
      image: registry.redhat.io/ubi8/nodejs-14:latest
      command:
        - /bin/sh
        - -c
      args:
        -  |-
          echo "Performing quality check"
          mkdir -p coverage
          mkdir -p reports/dependency-check
          dependency-check.sh --format ALL -s . --out reports/dependency-check --project "product-catalog-client"
          npm run sonar
          echo "Quality check complete, see results in sonarqube"
      env:
        - name: SONAR_SERVER_URL
          value: $(params.SONAR_SERVER_URL)
      workingDir: $(workspaces.source.path)
      volumeMounts:
        - name: dependency-cache
          mountPath: /opt/dependency-check/data
  volumes:
    - name: dependency-cache
      persistentVolumeClaim:
        claimName: dependency-cache