apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newName: quay.io/gnunn/client
  newTag: b8a2b2a-2774814127
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: c4d2e4a-2VInSCa42ebXFl5DVQ6Nt9iG7SX
resources:
- ../../../../environments/overlays/prod
