apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- patch.yaml

images:
- name: quay.io/gnunn/client
  newTag: latest
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: b0cbc2f-1371417504
resources:
- ../../../../environments/overlays/prod
