apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../environments/overlays/prod

patchesStrategicMerge:
- patch.yaml

images:
- name: quay.io/gnunn/client
  newTag: latest
- name: quay.io/gnunn/server
  newTag: latest