apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newTag: latest
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: 5e127e0-1958325436
resources:
- ../../../../environments/overlays/prod
