apiVersion: v1
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: maven-repo-creds
type: Opaque
data:
  MAVEN_SERVER_USERNAME: YWRtaW4K
  MAVEN_SERVER_PASSWORD: YWRtaW4xMjMK