apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../environments/overlays/prod

resources:
- user1-rolebinding.yaml

patchesStrategicMerge:
- patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: client
  path: patch-client-deployment.yaml

- target:
    group: apps
    version: v1
    kind: Deployment
    name: server
  path: patch-server-deployment.yaml
