apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: client
spec:
  workspaces:
    - name: git-source
  params:
    - name: git_revision
      type: string
      default: master
    - name: git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog-client
    - name: image_dest_url
      type: string
      description: External registry location to copy image to
      default: quay.io/gnunn/client
    - name: push-to-prod
      description: "Set to true if you want the pipeline to create a PR to push to prod"
      type: string
      default: "false"
    - name: cluster
      type: string
      description: Cluster to push to
      default: "local.home"
    - name: acs-secret
      description: Name of the secret with the central endpoint and api token. If not set no scan is done
      default: "ignore"
  tasks:
    - name: acquire-lease
      taskRef:
        name: acquire-lease
        kind: ClusterTask
      params:
        - name: lease-name
          value: "$(context.pipeline.name)"
        - name: owner
          value: "$(context.pipelineRun.name)"
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - acquire-lease
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.git_url)"
        - name: revision
          value: "$(params.git_revision)"
        - name: deleteExisting
          value: "true"
    - name: generate-id
      taskRef:
        name: generate-id
        kind: Task
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: git-source
    - name: build
      taskRef:
        name: npm
        kind: Task
      runAfter:
        - generate-id
      workspaces:
        - name: source
          workspace: git-source
    - name: quality
      taskRef:
        name: npm-quality
        kind: Task
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image
      taskRef:
        name: binary-s2i
        kind: Task
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - quality
      params:
        - name: directory
          value: "$(workspaces.source.path)/dist"
        - name: buildconfig
          value: client
    - name: tag-image
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: SCRIPT
          value: |
            echo "Taging image client@$(tasks.build-image.results.digest) to client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)"
            oc tag client@$(tasks.build-image.results.digest) client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
    - name: acs-scan-image
      taskRef:
        name: rox-image-scan
        kind: ClusterTask
      runAfter:
        - tag-image
      params:
        - name: rox_central_endpoint
          value: $(params.acs-secret)
        - name: rox_api_token
          value: $(params.acs-secret)
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: output_format
          value: table
      when:
        - input: "$(params.acs-secret)"
          operator: notin
          values: ["ignore"]
    - name: acs-check-image
      taskRef:
        name: rox-image-check
        kind: ClusterTask
      runAfter:
        - acs-scan-image
      params:
        - name: rox_central_endpoint
          value: $(params.acs-secret)
        - name: rox_api_token
          value: $(params.acs-secret)
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
      when:
        - input: "$(params.acs-secret)"
          operator: notin
          values: ["ignore"]
    - name: notify-on-scan-fail
      taskRef:
        name: send-to-webhook-slack
        kind: Task
      runAfter:
        - acs-check-image
      when:
        - input: "$(tasks.acs-check-image.results.check_passed)"
          operator: in
          values: ["false"]
      params:
        - name: webhook-secret
          value: slack-deployments-webhook
        - name: message
          value: "The image scan for client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) failed, please view test results here: https://central-stackrox.apps.home.ocplab.com/main/vulnerability-management/images/$(tasks.build-image.results.digest)"
    - name: push-dev-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - tag-image
      params:
        - name: src-image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-tags
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),dev
    - name: deploy-dev
      taskRef:
        name: run-tekton-pipeline
        kind: Task
      runAfter:
        - push-dev-image
      params:
        - name: pipeline
          value: gitops-deploy
        - name: args
          value: --use-param-defaults --param application=client --param environment=dev --prefix-name=client-gitops-deploy-dev --param tag=$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) --workspace name=manifest-source,claimName=manifest-source
    - name: push-test-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - deploy-dev
      params:
        - name: src-image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-tags
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),test,latest
    - name: deploy-test
      taskRef:
        name: run-tekton-pipeline
        kind: Task
      runAfter:
        - push-test-image
      params:
        - name: pipeline
          value: gitops-deploy
        - name: args
          value: --use-param-defaults --param application=client --param environment=test --prefix-name=client-gitops-deploy-test --param tag=$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) --workspace name=manifest-source,claimName=manifest-source
    - name: create-prod-pr
      taskRef:
        name: tkn
        kind: Task
      when:
        - input: "$(params.push-to-prod)"
          operator: in
          values: ["true","yes"]
      runAfter:
        - deploy-test
        - notify-on-scan-fail
      params:
        - name: commands
          value: |
            if ["$(params.acs-secret)" = "ignore"]; then
              echo "ACS was not enabled for this run"
              tkn pipeline start push-prod-pr --prefix-name client -p git_revision=pipelines-1.6 -p image_dest_tag=$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) -p image_dest_url=quay.io/gnunn/client -p cluster=$(params.cluster) -p app=client -s github-pipeline -w name=git-source,claimName=manifest-source
            else
              echo "ACS enabled, pass results"
              tkn pipeline start push-prod-pr --prefix-name client -p git_revision=pipelines-1.6 -p image_dest_tag=$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) -p image_dest_url=quay.io/gnunn/client -p cluster=$(params.cluster) -p app=server -p acs_image_scan_results=https://central-stackrox.apps.home.ocplab.com/main/vulnerability-management/images/$(tasks.build-image.results.digest) -s github-pipeline -w name=git-source,claimName=manifest-source
            fi
  finally:
    - name: release-lease
      taskRef:
        name: release-lease
        kind: ClusterTask
      params:
        - name: lease-name
          value: "$(context.pipeline.name)"
    - name: notify-on-fail
      taskRef:
        name: send-to-webhook-slack
        kind: Task
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      params:
        - name: webhook-secret
          value: slack-deployments-webhook
        - name: message
          value: "Some tasks in the $(context.pipeline.name) have failed in pipelinerun $(context.pipelinerun.name) failed, please investigate"
