apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: client
spec:
  workspaces:
    - name: git-source
    - name: gitops-manifests
    - name: slack-secret
      optional: true
    - name: acs-central
      optional: true
  params:
    - name: source_git_revision
      type: string
      default: master
    - name: source_git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog-client
    - name: gitops_git_revision
      type: string
      default: main
    - name: gitops_git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog
    - name: image_dest_url
      type: string
      description: External registry location to copy image to
      default: quay.io/gnunn/client
    - name: cluster
      type: string
      description: Cluster to push to
      default: "local.home"
  tasks:
    - name: acquire-lease
      taskRef:
        name: acquire-lease
        kind: ClusterTask
      params:
        - name: lease-name
          value: "$(context.pipeline.name)"
        - name: owner
          value: "$(context.pipelineRun.name)"
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - acquire-lease
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.source_git_url)"
        - name: revision
          value: "$(params.source_git_revision)"
        - name: deleteExisting
          value: "true"
    - name: generate-id
      taskRef:
        name: generate-id
        kind: Task
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: git-source
    - name: build
      taskRef:
        name: npm
        kind: Task
      runAfter:
        - generate-id
      workspaces:
        - name: source
          workspace: git-source
    - name: quality
      taskRef:
        name: npm-quality
        kind: Task
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image
      taskRef:
        name: binary-s2i
        kind: Task
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - quality
      params:
        - name: directory
          value: "$(workspaces.source.path)/dist"
        - name: buildconfig
          value: client
        - name: IMAGE
          value: $(params.image_dest_url)
    - name: acs-scan-image
      taskRef:
        name: rox-image-scan
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: output_format
          value: table
        - name: image
          value: $(params.image_dest_url)@$(tasks.build-image.results.IMAGE_DIGEST)
      when:
        - input: "$(workspaces.acs-central.bound)"
          operator: in
          values: ["true"]
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: acs-check-image
      taskRef:
        name: rox-image-check
        kind: ClusterTask
      runAfter:
        - acs-scan-image
      params:
        - name: image
          value: quay.io/gnunn/client@$(tasks.build-image.results.IMAGE_DIGEST)
      when:
        - input: "$(workspaces.acs-central.bound)"
          operator: in
          values: ["true"]
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: notify-on-scan-fail
      taskRef:
        name: send-to-webhook-slack
        kind: Task
      runAfter:
        - acs-check-image
      when:
        - input: "$(tasks.acs-check-image.results.check_passed)"
          operator: in
          values: ["false"]
      params:
        - name: message
          value: "The image scan for client:$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) failed, please view test results here: https://acs_central_host/main/vulnerability-management/images/$(tasks.build-image.results.IMAGE_DIGEST)"
      workspaces:
        - name: slack-secret
          workspace: slack-secret
    - name: tag-dev-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - build-image
      params:
        - name: src-image
          value: $(params.image_dest_url)@$(tasks.build-image.results.IMAGE_DIGEST)
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-tags
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),dev
    - name: clone-gitops-manifests
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - tag-dev-image
      workspaces:
        - name: output
          workspace: gitops-manifests
      params:
        - name: url
          value: "$(params.gitops_git_url)"
        - name: revision
          value: "$(params.gitops_git_revision)"
        - name: deleteExisting
          value: "true"
    - name: dev-update-image
      taskRef:
        name: update-image
      runAfter:
        - clone-gitops-manifests
      params:
        - name: git_revision
          value: "$(params.gitops_git_revision)"
        - name: path
          value: clusters/$(params.cluster)/overlays/dev
        - name: image
          value: "$(params.image_dest_url)"
        - name: image_tag
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
      workspaces:
        - name: gitops-manifests
          workspace: gitops-manifests
    - name: dev-gitops-deploy
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - dev-update-image
      params:
        - name: application-name
          value: product-catalog-dev
        - name: revision
          value: $(params.gitops_git_revision)
        - name: deployment
          value: client
        - name: namespace
          value: product-catalog-dev
        - name: image-tag
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
    - name: tag-test-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - dev-gitops-deploy
      params:
        - name: src-image
          value: $(params.image_dest_url)@$(tasks.build-image.results.IMAGE_DIGEST)
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-tags
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),test,latest
    - name: test-update-image
      taskRef:
        name: update-image
      runAfter:
        - tag-test-image
      params:
        - name: git_revision
          value: "$(params.gitops_git_revision)"
        - name: path
          value: clusters/$(params.cluster)/overlays/test
        - name: image
          value: "$(params.image_dest_url)"
        - name: image_tag
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
      workspaces:
        - name: gitops-manifests
          workspace: gitops-manifests
    - name: test-gitops-deploy
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - test-update-image
      params:
        - name: application-name
          value: product-catalog-test
        - name: revision
          value: $(params.gitops_git_revision)
        - name: deployment
          value: client
        - name: namespace
          value: product-catalog-test
        - name: image-tag
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
    - name: notify-build-complete
      taskRef:
        name: send-to-webhook-slack
        kind: Task
      runAfter:
        - test-gitops-deploy
        - notify-on-scan-fail
      params:
        - name: message
          value: |
            The build of image $(params.image_dest_url):$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid) has been completed
  finally:
    - name: release-lease
      taskRef:
        name: release-lease
        kind: ClusterTask
      params:
        - name: lease-name
          value: "$(context.pipeline.name)"
    - name: notify-on-fail
      taskRef:
        name: send-to-webhook-slack
        kind: Task
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
        - input: "$(workspaces.slack-secret.bound)"
          operator: in
          values: ["true"]
      params:
        - name: message
          value: "Some tasks in the $(context.pipeline.name) have failed in pipelinerun $(context.pipelinerun.name) failed, please investigate"
      workspaces:
        - name: slack-secret
          workspace: slack-secret