apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
# Client pipeline
- client-buildconfig.yaml
- client-pvc.yaml
- client-pipeline.yaml