apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-prod

bases:
- ../../../manifests/app/database/base
- ../../../manifests/app/server/base
- ../../../manifests/app/client/base

resources:
- namespace.yaml
- post-sync-pipeline-job.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: client
  path: patch-client-deployment.yaml

- target:
    group: apps
    version: v1
    kind: Deployment
    name: server
  path: patch-server-deployment.yaml
