apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-prod

resources:
- cicd-networkpolicy.yaml
- ../../../components/apps/database/base
- ../../../components/apps/server/base
- ../../../components/apps/client/base
- post-sync-pipeline-job.yaml