apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-prod

resources:
- ../../../components/app/database/base
- ../../../components/app/server/base
- ../../../components/app/client/base
- post-sync-pipeline-job.yaml

images:
- name: quay.io/gnunn/client
  newTag: latest
- name: quay.io/gnunn/server
  newTag: latest