apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- gitops-manifests-pvc.yaml
- github-pipeline-sa.yaml
- push-prod-pr-pipeline.yaml