apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: argocd-notification
spec:
  params:
  - name: state
    value: $(body.state)
  - name: application
    value: $(body.application)
  - name: description
    value: $(body.description)