---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: client
spec:
  serviceAccountName: pipeline
  triggers:
    - name: client-webhook
      bindings:
        - ref: github-triggerbinding
      template:
        ref: client
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: client-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: client
spec:
  port:
    targetPort: 8000
  to:
    kind: "Service"
    name: el-client
    weight: 100