---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: server
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-repo-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
        labels:
          tekton.dev/pipeline: server
        generateName: server-webhook-
      spec:
        pipelineRef:
          name: server
        params:
          - name: source_git_url
            #value: $(tt.params.git-repo-url)
            value: "https://github.com/gnunn-gitops/product-catalog-server"
          - name: source_git_revision
            value: $(tt.params.git-revision)
          - name: MAVEN_MIRROR_URL
            value: http://nexus:8081/content/groups/public/
          - name: push-to-prod
            value: "false"
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
          - name: gitops-manifests
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
          - name: maven-settings
            configmap:
              name: maven-settings
          - name: newman-env
            configMap:
              name: newman-env
