---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: slack-message
spec:
  params:
    - name: git_revision
      description: The git revision
      default: main
    - name: git_url
      description: The git repository url
    - name: git_source_url
      description: The git repository source code URL
    - name: image_dest_url
      description: External registry location of image to push without tag
    - name: image_dest_tag
      description: Tag of image to push to production
    - name: cluster
      description: Cluster to push to
    - name: app
      description: Either 'server' or 'client'
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: push-prod-pr
        generateName: slack-message-webhook-
      spec:
        pipelineRef:
          name: push-prod-pr
        params:
          - name: git_url
            value: $(tt.params.git_url)
          - name: git_revision
            value: $(tt.params.git_revision)
          - name: git_source_url
            value: $(tt.params.git_source_url)
          - name: image_dest_tag
            value: $(tt.params.image_dest_tag)
          - name: image_dest_url
            value: $(tt.params.image_dest_url)
          - name: cluster
            value: $(tt.params.cluster)
          - name: app
            value: $(tt.params.app)
        workspaces:
          - name: gitops-manifests
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
          - name: acs-central
            secret:
              secretName: roxsecrets          