apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: slack-message
spec:
  params:
    - name: git_revision
      value: $(body.git_revision)
    - name: git_url
      value: $(body.git_url)
    - name: git_source_url
      value: $(body.git_source_url)
    - name: image_dest_url
      value: $(body.image_dest_url)
    - name: image_dest_tag
      value: $(body.image_dest_tag)
    - name: cluster
      value: $(body.cluster)
    - name: app
      value: $(body.app)
