apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog-test
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: apps-product-catalog
  source:
    path: manifests/app/overlays/test-quay
    repoURL: https://github.com/gnunn-gitops/product-catalog.git
    targetRevision: master
  info:
  - name: Environment
    value: Test
  - name: Owner
    value: "Gerald Nunn"
  - name: Contact
    value: "gnunn@somewhere.com"
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress