apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: product-catalog-cicd
  name: product-catalog-cicd
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: product-catalog-cicd